export {
  sendBookingConfirmationToCustomer,
  sendBookingReceivedToCustomer,
  sendNewBookingNotificationToBusiness,
  sendBookingCancelledNotification,
  sendBookingConfirmedNotification,
  sendReviewRequestNotification,
  sendNotificationSafely,
  sendMultiNotificationSafely,
  getBusinessReplyToEmail,
  sendReminderEmail,
  sendBookingReminderNotification,
  sendBookingCancelledNotificationById,
  sendPaymentReceivedNotification,
  sendLoyaltyRewardNotification,
} from './email-provider'
export {
  buildWhatsappUrl,
  buildBookingConfirmationWhatsappMessage,
  buildReviewRequestWhatsappMessage,
  buildWhatsappBookingSummaryText,
  buildWhatsappReminderMessage,
  buildWhatsappReminderUrl,
} from './whatsapp'
export {
  BOOKING_CONFIRMED_TEMPLATE,
  BOOKING_REMINDER_TEMPLATE,
  BOOKING_CANCELLED_TEMPLATE,
  PAYMENT_RECEIVED_TEMPLATE,
  bookingConfirmationCustomerHtml,
  bookingConfirmationCustomerText,
  bookingReceivedCustomerHtml,
  bookingReceivedCustomerText,
  newBookingBusinessHtml,
  newBookingBusinessText,
  bookingCancelledCustomerHtml,
  bookingCancelledCustomerText,
  reviewRequestHtml,
  reviewRequestText,
  bookingReminderHtml,
  bookingReminderText,
  paymentReceivedHtml,
  paymentReceivedText,
  loyaltyRewardHtml,
  loyaltyRewardText,
} from './templates'
export type { EmailResult, BookingEmailData, CancellationEmailData, ReviewRequestEmailData, NewBookingBusinessEmailData, ReminderEmailData, LoyaltyRewardEmailData, NotificationResult } from './types'
export type { BookingWhatsappData, ReviewRequestWhatsappData } from './whatsapp'
