import Link from 'next/link'
import { ArrowLeft, ArrowRight, CircleAlert, CreditCard, Eye, Gauge, Waypoints } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { MetricCard } from './metric-card'
import { TrendChart } from './trend-chart'
import { FunnelChart } from './funnel-chart'
import { AnalyticsTables, type AnalyticsPagination } from './analytics-tables'
import { AcquisitionLinks } from './acquisition-links'
import type { OwnerAnalyticsReport } from '@/server/analytics/reports'
import { AnalyticsControls } from './analytics-controls'
import { AnalyticsCaptureControl } from './analytics-capture-control'
import { FlowBreakdowns } from './flow-breakdowns'

function ratioText(value: { numerator: number; denominator: number; rate: number | null }) { return value.rate === null ? 'Sin datos' : `${Math.round(value.rate * 100)}%` }
function ratioDetail(value: { numerator: number; denominator: number; rate: number | null }, subject: string) { return value.rate === null ? `Sin datos para ${subject}` : `${ratioText(value)} · ${value.numerator} de ${value.denominator} ${subject}` }
const bookingStatusLabels: Record<string, string> = { pending_confirmation: 'Pendiente de confirmación', pending_payment: 'Pendiente de pago', confirmed: 'Confirmada', cancelled: 'Cancelada', completed: 'Completada', no_show: 'No asistió', hold_expired: 'Reserva vencida', refunded: 'Reembolsada' }
const redemptionStatusLabels: Record<string, string> = { applied: 'Aplicado', released: 'Liberado' }
const lastStepLabels: Record<string, string> = { started: 'Inicio', service: 'Servicio', professional: 'Profesional (opcional)', date: 'Fecha', time: 'Hora', customer: 'Datos de reserva', payment: 'Pago', submit: 'Envío' }
const populationLabels: Record<string, string> = { complete_attempts: 'entrada completa', partial_attempts: 'entrada parcial' }
const reasonLabels: Record<string, string> = { no_slots: 'Sin horarios', outside_window: 'Fuera del plazo permitido', outside_booking_window: 'Fuera del plazo de reserva', lead_time_restricted: 'Anticipación insuficiente', not_offered: 'Servicio no ofrecido', no_capacity: 'Sin capacidad disponible', unknown: 'Motivo desconocido' }

function PopulationEvidence({ summary, recent = false }: { summary: Pick<OwnerAnalyticsReport, 'complete' | 'partial'>; recent?: boolean }) {
  return <div className="grid gap-4 sm:grid-cols-2">{(['complete', 'partial'] as const).map(kind => {
    const population = summary[kind]
    return <section key={kind} aria-label={`${recent ? 'Provisional: ' : ''}entrada ${kind === 'complete' ? 'completa' : 'parcial'}`} className="space-y-2 rounded-xl border border-border p-4 text-sm">
      <h3 className="font-semibold text-primary">Entrada {kind === 'complete' ? 'completa' : 'parcial'}{recent ? ' · provisional' : ''}</h3>
      <p>{population.attempts} intentos observados · {ratioDetail(population.conversion, kind === 'complete' ? 'intentos completos' : 'intentos parciales')}</p>
      <p>{population.bookingsCreated} reservas creadas · {population.pathComplete} conversiones con recorrido completo · {population.pathIncomplete} con recorrido incompleto.</p>
      <p>{population.conversion.numerator} convertidos + {population.knownInterruptions} interrupciones conocidas + {population.measurementIncomplete} con medición incompleta = {population.conversion.denominator} intentos maduros.</p>
      <p className="text-muted-foreground">No completaron en 24 h; la medición incompleta no se asigna a un paso ni indica una causa.</p>
      <p>Disponibilidad vacía: {ratioDetail(population.availabilityEmpty, 'intentos con búsqueda')}.</p><p>Errores de disponibilidad: {population.availabilityErrors} intentos.</p>
    </section>
  })}</div>
}
function OriginEvidence({ label, summary }: { label: string; summary: OwnerAnalyticsReport['channels']['rows'][number]['summary'] }) {
  return <div className="border-b border-border py-2"><p className="font-medium">{label}</p><p>{summary.visits} visitas · {summary.complete.attempts} intentos completos · {summary.partial.attempts} intentos parciales</p><p>Completa: {ratioDetail(summary.complete.conversion, 'intentos completos')}. Parcial: {ratioDetail(summary.partial.conversion, 'intentos parciales')}.</p></div>
}

function coverageText(report: OwnerAnalyticsReport) { return report.coverage.status === 'unavailable' ? 'Datos no disponibles: no se puede confirmar una serie madura para este período.' : report.coverage.status === 'disabled' ? 'La captura estuvo deshabilitada durante este período; los espacios sin registro no equivalen a cero.' : report.coverage.status === 'partial' ? 'Cobertura parcial: interpreta cada cohorte marcada con cautela.' : 'Cobertura completa para las cohortes maduras disponibles.' }
function filterLabel(report: OwnerAnalyticsReport) { const f = report.filter; return f.channel ? `Canal: ${f.channel}` : f.acquisitionLinkId ? `Enlace: ${f.acquisitionLinkId}` : f.serviceId ? `Servicio: ${f.serviceId}` : 'Sin filtro histórico' }
function dateTime(value: string, timezone: string) { return new Intl.DateTimeFormat('es-CL', { timeZone: timezone, dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
export type AnalyticsPeriodMode = { days: 7 | 28 | 90 } | { days: null }
export function buildMetricsHref(report: OwnerAnalyticsReport, periodMode: AnalyticsPeriodMode, page: number, days?: 7 | 28 | 90) { const p = new URLSearchParams(); const preset = days ?? periodMode.days; if (preset) p.set('days', String(preset)); else { p.set('from', report.period.from); p.set('to', report.period.to) }; p.set('page', String(page)); p.set('pageSize', String(report.services.pageSize)); for (const [key, value] of Object.entries({ channel: report.filter.channel, acquisitionLinkId: report.filter.acquisitionLinkId, serviceId: report.filter.serviceId })) if (value) p.set(key, value); return `/dashboard/metricas?${p}` }
function pagination(report: OwnerAnalyticsReport, periodMode: AnalyticsPeriodMode, current: number, hasNext: boolean, label: string): AnalyticsPagination { return { label, previousHref: current > 1 ? buildMetricsHref(report, periodMode, current - 1) : null, nextHref: hasNext ? buildMetricsHref(report, periodMode, current + 1) : null } }
function PageControls({ pagination: p, nextLabel }: { pagination: AnalyticsPagination; nextLabel: string }) { return <div className="flex items-center justify-between gap-2 text-xs text-muted-foreground"><span>{p.label}</span>{p.previousHref && <Button asChild variant="outline" size="sm"><Link href={p.previousHref}><ArrowLeft />Anterior</Link></Button>}{p.nextHref && <Button asChild variant="outline" size="sm"><Link href={p.nextHref}>{nextLabel}<ArrowRight /></Link></Button>}</div> }

export function AnalyticsDashboard({ report, periodMode = { days: null } }: { report: OwnerAnalyticsReport; periodMode?: AnalyticsPeriodMode }) {
  const unavailable = report.coverage.status === 'unavailable'
  const hasClosedData = !unavailable && (report.complete.attempts > 0 || report.partial.attempts > 0 || report.visits > 0)
  const hasApplicableRecent = report.recent.status === 'provisional' && report.recent.from < report.recent.to
  const currentStates = report.currentBookings.counts.map((row) => `${bookingStatusLabels[row.status] ?? row.status}: ${row.count}`).join(' · ') || 'Sin estados en este período.'
  const servicePagination = pagination(report, periodMode, report.services.page, report.services.page * report.services.pageSize < report.services.total, `Página ${report.services.page} de ${Math.max(1, Math.ceil(report.services.total / report.services.pageSize))}`)
  const linksPagination = pagination(report, periodMode, report.links.page, report.links.page * report.links.pageSize < report.links.total, `Página ${report.links.page} de ${Math.max(1, Math.ceil(report.links.total / report.links.pageSize))}`)
  const redemptionPagination = pagination(report, periodMode, report.redemptions.page, report.redemptions.hasMore, `Página ${report.redemptions.page}${report.redemptions.hasMore ? ' · hay más resultados' : ''}`)
  const acquisitionPagination = pagination(report, periodMode, report.acquisitionLinks.page, report.acquisitionLinks.page * report.acquisitionLinks.pageSize < report.acquisitionLinks.total, `Página ${report.acquisitionLinks.page} de ${Math.max(1, Math.ceil(report.acquisitionLinks.total / report.acquisitionLinks.pageSize))}`)
  const historicalScope = `Histórico: ${filterLabel(report)}. Los granos no se intersectan.`

  return <div className="space-y-8 p-5 pb-24 md:p-10">
    <AnalyticsControls key={JSON.stringify([report.period.from, report.period.to, periodMode.days, report.filter])} report={report} periodMode={periodMode} />
    <AnalyticsCaptureControl capture={report.capture} />
    <div className="flex flex-col gap-4 rounded-xl border border-border bg-card p-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="text-sm font-semibold text-primary">{coverageText(report)}</p><p className="mt-1 text-xs text-muted-foreground">Período seleccionado: {report.period.from} a {report.period.to} · Zona: {report.period.timezone} · Corte: {dateTime(report.period.cutoffAt, report.period.timezone)} ({report.period.timezone}) · Activación: {report.capture.activatedAt ? dateTime(report.capture.activatedAt, report.period.timezone) : 'sin activación registrada'}.</p><p className="mt-1 text-xs text-muted-foreground">Filtro activo: {filterLabel(report)}.</p></div><div className="flex flex-wrap gap-2" aria-label="Seleccionar período">{([7, 28, 90] as const).map(days => <Button key={days} asChild variant="outline" size="sm"><Link href={buildMetricsHref(report, periodMode, 1, days)}>{days} días</Link></Button>)}</div></div>
    {report.coverage.warnings.length > 0 && <ul className="rounded-xl border border-border bg-secondary/25 p-4 text-sm text-muted-foreground" aria-label="Advertencias de cobertura">{report.coverage.warnings.map(w => <li key={w}>• {w}</li>)}</ul>}
    {unavailable ? <Card className="border-destructive/30"><CardHeader><CardTitle><CircleAlert className="mr-2 inline size-5 text-destructive" />Datos no disponibles</CardTitle><CardDescription>Este error no se presenta como una serie de ceros.</CardDescription></CardHeader></Card> : !hasClosedData ? <Card><CardHeader><CardTitle>Aún no hay datos maduros</CardTitle><CardDescription>La captura puede estar inactiva o las ventanas aún están en curso; no se inventan valores.</CardDescription></CardHeader></Card> : <>
      <section aria-label="Resumen de métricas" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Visitas" value={String(report.visits)} detail={ratioDetail(report.visitToAttempt, 'visitas llegan a intento')} /><MetricCard label="Intentos completos" value={String(report.complete.attempts)} detail="Medidos desde el primer paso" /><MetricCard label="Conversión en 24 h" value={ratioText(report.complete.conversion)} detail={`${report.complete.conversion.numerator} de ${report.complete.conversion.denominator} intentos`} /><MetricCard label="Reservas creadas · entrada completa" value={String(report.complete.bookingsCreated)} detail="Puede haber más de una por conversión" /></section>
      <PopulationEvidence summary={report} />
      <section className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><Card><CardHeader><CardTitle>Tendencia</CardTitle><CardDescription>{historicalScope}</CardDescription></CardHeader><CardContent><TrendChart trend={report.trend} coverage={report.coverage.cohorts} unavailable={false} /></CardContent></Card><Card><CardHeader><CardTitle>Entrada y madurez</CardTitle><CardDescription>Completa = desde el primer paso. Parcial = restauración o consentimiento a mitad de flujo.</CardDescription></CardHeader><CardContent className="space-y-3 text-sm"><p>{report.complete.attempts} intentos completos</p><p>{report.partial.attempts} intentos parciales</p><p className="rounded-lg bg-secondary/40 p-3 text-muted-foreground">Comparación: {report.comparison.status === 'comparable' && report.comparison.deltaPercentagePoints !== null ? `${report.comparison.deltaPercentagePoints > 0 ? '+' : ''}${report.comparison.deltaPercentagePoints} puntos porcentuales` : 'no comparable por cobertura o falta de datos.'}</p></CardContent></Card></section>
      <section className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle><Waypoints className="mr-2 inline size-5" />Recorrido observado</CardTitle><CardDescription>{historicalScope} Profesional es opcional.</CardDescription></CardHeader><CardContent><FunnelChart funnel={report.funnel} complete={report.complete} unavailable={false} /></CardContent></Card><Card><CardHeader><CardTitle>Último paso observado</CardTitle><CardDescription>{historicalScope}</CardDescription></CardHeader><CardContent><ul className="space-y-2">{report.quality.map(row => <li key={`${row.population}-${row.lastStep}`} className="flex justify-between gap-4 rounded-lg bg-secondary/30 px-3 py-2 text-sm"><span>{lastStepLabels[row.lastStep] ?? row.lastStep} · {populationLabels[row.population] ?? row.population}</span><span className="font-mono">{row.count}</span></li>)}</ul></CardContent></Card></section>
      <AnalyticsTables report={report} pagination={servicePagination} />
      <section className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Origen y canjes</CardTitle><CardDescription>Canales y enlaces son granos históricos independientes; canjes son operativos y no responden al filtro histórico.</CardDescription></CardHeader><CardContent className="space-y-4 text-sm"><div><h3 className="font-medium">Canales observados</h3>{report.channels.rows.map(row => <OriginEvidence key={row.id} label={row.id} summary={row.summary} />)}</div><div><h3 className="font-medium">Enlaces agregados</h3>{report.links.rows.map(row => <OriginEvidence key={row.id} label={row.label} summary={row.summary} />)}<PageControls pagination={linksPagination} nextLabel="Siguiente enlaces agregados" /></div><div><h3 className="font-medium">{report.redemptions.label}</h3>{report.redemptions.rows.map(row => <p key={`${row.promotionId}-${row.status}`}>{row.label}: {redemptionStatusLabels[row.status] ?? row.status} · {row.count}</p>)}<PageControls pagination={redemptionPagination} nextLabel="Siguiente canjes" /></div></CardContent></Card>
      <Card><CardHeader><CardTitle>Estados actuales de reservas</CardTitle><CardDescription>{report.currentBookings.label}; operativo, independiente de filtros históricos.</CardDescription></CardHeader><CardContent className="space-y-3 text-sm"><p>{currentStates}</p><p>Cola de aprobación vencida: {report.currentBookings.overdueApproval.lowerBound ? 'al menos ' : ''}{report.currentBookings.overdueApproval.count}</p><Link href="/dashboard/bookings" className="text-primary underline">Revisar reservas</Link></CardContent></Card></section>
    </>}
    <FlowBreakdowns report={report.flowBreakdowns} />
    {!hasClosedData && <Card><CardHeader><CardTitle>Estados actuales de reservas</CardTitle><CardDescription>{report.currentBookings.label}; operativo, independiente de filtros históricos.</CardDescription></CardHeader><CardContent className="space-y-3 text-sm"><p>{currentStates}</p><p>Cola de aprobación vencida: {report.currentBookings.overdueApproval.lowerBound ? 'al menos ' : ''}{report.currentBookings.overdueApproval.count}</p><Link href="/dashboard/bookings" className="text-primary underline">Revisar reservas</Link></CardContent></Card>}
    <section><h2 className="font-heading text-2xl font-semibold text-primary">Oportunidades para revisar</h2><p className="text-sm text-muted-foreground">{report.opportunityNote}</p>{report.opportunities.length === 0 ? <Card className="mt-3"><CardContent className="py-4 text-sm text-muted-foreground">No hay señales que superen los umbrales observados.</CardContent></Card> : <div className="mt-3 grid gap-3 md:grid-cols-3">{report.opportunities.map(o => <Card key={o.key}><CardHeader><CardTitle className="text-base">{o.key === 'overdue_approval' ? 'Aprobaciones vencidas' : 'Disponibilidad observada'}</CardTitle><CardDescription>{o.message}</CardDescription></CardHeader><CardContent className="space-y-2 text-sm"><p>Evidencia: {o.denominator === null ? `${o.numerator} casos` : `${o.numerator} de ${o.denominator} (${ratioText({ numerator: o.numerator, denominator: o.denominator, rate: o.rate })})`}</p>{o.diagnostics.status === 'available' ? <><p>Diagnóstico retenido: {o.diagnostics.converted ?? 0} con conversión.</p>{Object.entries(o.diagnostics.reasons).map(([reason, count]) => <p key={reason}>{reasonLabels[reason] ?? 'Motivo no clasificado'}: {count}</p>)}</> : <p className="text-muted-foreground">{o.diagnostics.status === 'not_queried' ? 'Detalle no consultado para este rango o filtro; no implica que haya sido purgado.' : o.diagnostics.status === 'not_retained' ? 'Detalle histórico no retenido.' : 'Diagnóstico no aplicable a esta señal.'}</p>}<Button asChild size="sm" variant="outline"><Link href={o.href}>Revisar <ArrowRight /></Link></Button></CardContent></Card>)}</div>}</section>
    {hasApplicableRecent ? <Card><CardHeader><CardTitle><Gauge className="mr-2 inline size-5" />Período reciente en curso</CardTitle><CardDescription>{report.recent.from} a {report.recent.to}; {report.recent.inProgress.complete} completo(s) y {report.recent.inProgress.partial} parcial(es) aún no entran al denominador maduro.</CardDescription></CardHeader><CardContent className="space-y-3"><p className="text-sm">{report.recent.visits} visitas recientes · {ratioDetail(report.recent.visitToAttempt, 'visitas llegan a intento')} · datos provisionales al corte.</p><PopulationEvidence summary={report.recent} recent /></CardContent></Card> : <Card><CardHeader><CardTitle>{report.recent.status === 'unavailable' ? 'Datos recientes no disponibles' : 'No hay días recientes aplicables'}</CardTitle></CardHeader></Card>}
    <Card><CardHeader><CardTitle><Eye className="mr-2 inline size-5" />Privacidad y alcance</CardTitle><CardDescription>{report.suppression.note}</CardDescription></CardHeader><CardContent><Link href="/dashboard/payments" className="text-primary underline"><CreditCard className="mr-1 inline size-4" />Ver pagos registrados</Link></CardContent></Card>
    <AcquisitionLinks links={report.acquisitionLinks} pagination={acquisitionPagination} />
  </div>
}
